
title = "Start Bootstrap Clean Blog"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en-us"
copyright = "Code released under the Apache 2.0 license."

[author]
    name = "Mile Auto"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Your site description"
  Author = "Mile Auto"
  email = "ajmalroshantest@gmail.com"
  Ganalytics = "XX-00000000-0"
  # This will load all the CSS defined in the list
  # customCSS = ["<absolute path to CSS>", "/static/css/test.css", "<or just load it off the internet>"]
  coverImage = "/images/uploads/home-bg.jpg"

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/"
[[params.social]]
    title = "github"
    url = "https://github.com/"
[[params.social]]
    title = "facebook"
    url = "https://www.facebook.com/"

[[menu.main]]
  name = "Archives"
  url = "/posts/"
  weight = -160

[[menu.main]]
  name = "Home"
  type= "home"
  url= "/"
  weight= -190