backend:
  name: bitbucket
  repo: ajmalroshantest/mileblog

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home"
        name: "home"
        fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Publish Date", name: "date", widget: "datetime"}
        - {label: "Cover Image", name: "coverImage", required: false, widget: "image", default: "/images/uploads/home-bg.jpg"}
        - {label: "Description", name: "description", widget: "string"}

      - file: "content/about.md"
        label: "About"
        name: "about"
        fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Publish Date", name: "date", widget: "datetime"}  
        - {label: "Cover Image", name: "coverImage", required: false, widget: "image", default: "/images/uploads/about-bg.jpg"}
        - {label: "Description", name: "description", widget: "string"}
        - {label: "Menu", name: "menu", widget: "string"}
        - {label: "Type", name: "type", widget: "string"}
        - {label: "Weight", name: "weight", widget: "string"}

      - file: "content/contact.md"
        label: "Contact"
        name: "contact"
        fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Publish Date", name: "date", widget: "datetime"} 
        - {label: "Cover Image", name: "coverImage", required: false, widget: "image", default: "/images/uploads/contact-bg.jpg"}
        - {label: "Description", name: "description", widget: "string"}
        - {label: "Menu", name: "menu", widget: "string"}
        - {label: "Type", name: "type", widget: "string"}
        - {label: "Weight", name: "weight", widget: "string"}

  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Publish Date"
        name: "date"
        required: false
        widget: "datetime"

      - label: "Categories"
        name: "categories"
        required: false
        widget: "list"

      - label: "Tags"
        name: "tags"
        required: false
        widget: "list"

      - label: "Keywords"
        name: "keywords"
        required: false
        widget: "list"

      - label: "Auto Thumbnail Image"
        name: "autoThumbnailImage"
        required: false
        widget: "boolean"
        default: false

      - label: "Thumbnail Image Position"
        name: "thumbnailImagePosition"
        required: false
        widget: "select"
        default: "top"
        options: ["left", "top", "right"]
        
      - label: "Thumbnail Image"
        name: "thumbnailImage"
        required: false
        widget: "image"

      - label: "Cover Image"
        name: "coverImage"
        required: false
        widget: "image"
        default: "/images/uploads/home-bg.jpg"
        
      - label: "Body"
        name: "body"
        widget: "markdown"